### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Russole** [KlaineWei/MoCo4SRec#1]
Hello, thank you for providing the program. When I ran the program, I encountered the following error: 

[Errno 2] No such file or directory: 'output/cutshuffle\MoCo4SRec-Beauty.txt'

**Comment by KlaineWei** [comment]
You need to pay attention to the relative path. The slashes near cutshuffle are different.

**Comment by Russole** [comment]
When I tried to run the program on the Beauty dataset and changed the path, I still encountered the following error.

Traceback (most recent call last):
  File "main.py", line 237, in <module>
    main()
  File "main.py", line 163, in main
    with open(args.log_file, 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output/cutshuffle/MoCo4SRec-Beauty.txt'

**Comment by KlaineWei** [comment]
Sorry for replying late.You need to create the dirs manually.

**Comment by Russole** [comment]
Thank you for your reply，
Line 227 of src/models.py, The arguments name "noise" in the function should be changed to "usenoise".
After changing it, the program can run normally
